config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('licenciatura', views.licenciatura_page_view, name='licenciatura'),
    path('licenciatura_nova_cadeira', views.licenciatura_nova_cadeira_view, name='licenciatura_nova_cadeira'),
    path('licenciatura_edita_cadeira/<int:cadeira_id>', views.licenciatura_edita_cadeira_view, name='licenciatura_edita_cadeira'),
    path('licenciatura_apaga_cadeira/<int:cadeira_id>', views.licenciatura_apaga_cadeira_view, name='licenciatura_apaga_cadeira'),

    path('aptidoes', views.aptidoesecompetencias_page_view, name='aptidoes'),
    path('nova_aptidao', views.nova_aptidao_view, name='nova_aptidao'),
    path('edita_aptidao/<int:aptidao_id>', views.edita_aptidao_view, name='edita_aptidao'),
    path('apaga_aptidao/<int:aptidao_id>', views.apaga_aptidao_view, name='apaga_aptidao'),

    path('projetos', views.projetos_page_view, name='projetos'),
    path('novo_projeto', views.novo_projeto_view, name='novo_projeto'),
    path('edita_projeto/<int:projeto_id>', views.edita_projeto_view, name='edita_projeto'),
    path('apaga_projeto/<int:projeto_id>', views.apaga_projeto_view, name='apaga_projeto'),

    path('programacaowebtecnologias', views.programacaowebtecnologias_page_view, name='programacaowebtecnologias'),
    path('nova_tecnologia', views.nova_tecnologia_view, name='nova_tecnologia'),
    path('edita_tecnologia/<int:tecnologia_id>', views.edita_tecnologia_view, name='edita_tecnologia'),
    path('apaga_tecnologia/<int:tecnologia_id>', views.apaga_tecnologia_view, name='apaga_tecnologia'),

    path('blog', views.blog_page_view, name='blog'),
    path('novo_post', views.novo_post_view, name='novo_post'),
    path('edita_post/<int:post_id>', views.edita_post_view, name='edita_post'),
    path('apaga_post/<int:post_id>', views.apaga_post_view, name='apaga_post'),

    path('sobreestewebsite', views.sobreestewebsite_page_view, name='sobreestewebsite'),

    path('contactos', views.contactos_page_view, name='contactos'),

    path('laboratorios', views.laboratorios_page_view, name='laboratorios'),
    path('novo_laboratorio', views.novo_laboratorio_view, name='novo_laboratorio'),
    path('edita_laboratorio/<int:laboratorio_id>', views.edita_laboratorio_view, name='edita_laboratorio'),
    path('apaga_laboratorio/<int:laboratorio_id>', views.apaga_laboratorio_view, name='apaga_laboratorio'),

    path('noticias', views.noticias_page_view, name='noticias'),
    path('nova_noticia', views.nova_noticia_view, name='nova_noticia'),
    path('edita_noticia/<int:noticia_id>', views.edita_noticia_view, name='edita_noticia'),
    path('apaga_noticia/<int:noticia_id>', views.apaga_noticia_view, name='apaga_noticia'),

    path('exemplosetecnicas', views.exemplosetecnicas_page_view, name='exemplosetecnicas'),

    path('quizz', views.quizz_page_view, name='quizz'),

    path('educacao', views.educacao_page_view, name='educacao'),
    path('nova_escola', views.nova_escola_view, name='nova_escola'),
    path('edita_escola/<int:escola_id>', views.edita_escola_view, name='edita_escola'),
    path('apaga_escola/<int:escola_id>', views.apaga_escola_view, name='apaga_escola'),

    path('certificados', views.certificados_page_view, name='certificados'),

    path('outrashabilitacoes', views.outrashabilitacoes_page_view, name='outrashabilitacoes'),

    path('aptidoesecompetencias', views.aptidoesecompetencias_page_view, name='aptidoesecompetencias'),

    path('interessesehobbies', views.interessesehobbies_page_view, name='interessesehobbies'),

    path('novo_interesse', views.novo_interesse_view, name='novo_interesse'),
    path('edita_interesse/<int:interesse_id>', views.edita_interesse_view, name='edita_interesse'),
    path('apaga_interesse/<int:interesse_id>', views.apaga_interesse_view, name='apaga_interesse'),

    path('tfcs', views.tfcs_page_view, name='tfcs'),
    path('novo_tfc', views.novo_tfc_view, name='novo_tfc'),
    path('edita_tfc/<int:tfc_id>', views.edita_tfc_view, name='edita_tfc'),
    path('apaga_tfc/<int:tfc_id>', views.apaga_tfc_view, name='apaga_tfc'),

    path('login/', views.login_page_view, name='login'),
    path('logout/', views.logout_page_view, name='logout'),
]

portfolio/forms.py
from django.forms import ModelForm
from django import forms

from portfolio.models import Cadeira, Projeto, Tecnologia, Noticia, Laboratorio, Interesse, Escola, BlogPost, \
    AptidoesECompetencia, TFC


class CadeiraForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = Cadeira
        fields = '__all__'


class AptidoesECompetenciaForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = AptidoesECompetencia
        fields = '__all__'


class ProjetoForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = Projeto
        fields = '__all__'


class TecnologiaForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = Tecnologia
        fields = '__all__'


class NoticiaForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = Noticia
        fields = '__all__'


class LaboratorioForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = Laboratorio
        fields = '__all__'


class InteresseForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = Interesse
        fields = '__all__'


class EscolaForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = Escola
        fields = '__all__'


class BlogPostForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = BlogPost
        fields = '__all__'


class TFCForm(ModelForm):
    descricao = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = TFC
        fields = '__all__'

portfolio/views.py
import collections

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from django.urls import reverse
import matplotlib.pyplot as plt

from portfolio.forms import CadeiraForm, ProjetoForm, TecnologiaForm, NoticiaForm, LaboratorioForm, InteresseForm, \
    EscolaForm, BlogPostForm, AptidoesECompetenciaForm, TFCForm
from portfolio.models import Cadeira, Projeto, Escola, Interesse, Pessoa, Linguagen, Tecnologia, Laboratorio, Noticia, \
    PontuacaoQuizz, resolution_path, BlogPost, AptidoesECompetencia, TFC


def home_page_view(request):
    return render(request, 'portfolio/home.html')


def licenciatura_page_view(request):
    elementos = Cadeira.objects.all()

    for elemento in elementos:
        elemento.__dict__["professorPraticas"] = list(Pessoa.objects.filter(praticas__id=elemento.id))
        elemento.__dict__["professorTeoricas"] = list(Pessoa.objects.filter(teoricas__id=elemento.id))
        elemento.__dict__["linguagemUtilizada"] = list(Linguagen.objects.filter(linguagem__id=elemento.id))
        elemento.__dict__["projetoRealizado"] = list(Projeto.objects.filter(projeto__id=elemento.id))

    return render(request, 'portfolio/licenciatura.html', {"cadeiras": elementos})


def aptidoesecompetencias_page_view(request):
    elementos = AptidoesECompetencia.objects.all()

    for elemento in elementos:
        elemento.__dict__["projetoRealizado"] = list(Projeto.objects.filter(projetos__id=elemento.id))
        elemento.__dict__["cadeiras"] = list(Cadeira.objects.filter(disciplinas__id=elemento.id))

    return render(request, 'portfolio/aptidoesecompetencias.html', {"aptidoes": elementos})


def projetos_page_view(request):
    elementos = Projeto.objects.all()

    for elemento in elementos:
        elemento.__dict__["linguagemUsada"] = list(Linguagen.objects.filter(linguagemUsada__id=elemento.id))
        elemento.__dict__["autores"] = list(Pessoa.objects.filter(participantes__id=elemento.id))

    return render(request, 'portfolio/projetos.html', {"projetos": elementos})


def programacaowebtecnologias_page_view(request):
    elementos = Tecnologia.objects.all()

    return render(request, 'portfolio/programacaowebtecnologias.html', {"tecnologias": elementos})


def blog_page_view(request):
    elementos = BlogPost.objects.all()

    return render(request, 'portfolio/blog.html', {"posts": elementos})


def sobreestewebsite_page_view(request):
    return render(request, 'portfolio/sobreestewebsite.html')


def contactos_page_view(request):
    return render(request, 'portfolio/contactos.html')


def laboratorios_page_view(request):
    elementos = Laboratorio.objects.all()

    return render(request, 'portfolio/laboratorios.html', {"laboratorios": elementos})


def noticias_page_view(request):
    elementos = Noticia.objects.all()

    return render(request, 'portfolio/noticias.html', {"noticias": elementos})


def exemplosetecnicas_page_view(request):
    return render(request, 'portfolio/exemplosetecnicas.html')


def quizz_page_view(request):
    if request.method == 'POST':
        n = request.POST['nome']
        p: int = 0

        if collections.Counter(request.POST.getlist("linguagem[]")) == collections.Counter(
                ("css", "html", "javascript")):
            p = p + 1

        if request.POST["opcao"] == "img":
            p = p + 1

        if request.POST["datecriacao"] == "2005-07-21":
            p = p + 1

        if request.POST["pagecolor"] == "#ffffff":
            p = p + 1

        if request.POST["launchYear"] == "1993":
            p = p + 1

        r = PontuacaoQuizz(nome=n, pontuacao=p)
        r.save()

    languages_x = []
    popularity_y = []
    for pontuacao in PontuacaoQuizz.objects.all():
        languages_x.append(pontuacao.nome)
        popularity_y.append(pontuacao.pontuacao)

    languages_x.reverse()
    popularity_y.reverse()
    plt.barh(languages_x, popularity_y)
    plt.savefig('portfolio/static/portfolio/images/graph.png', bbox_inches='tight')
    plt.close()

    return render(request, 'portfolio/quizz.html')


def educacao_page_view(request):
    return render(request, 'portfolio/educacao.html', {"escolas": Escola.objects.all()})


def certificados_page_view(request):
    return render(request, 'portfolio/certificados.html')


def outrashabilitacoes_page_view(request):
    return render(request, 'portfolio/outrashabilitacoes.html')


def interessesehobbies_page_view(request):
    return render(request, 'portfolio/interessesehobbies.html', {"interesses": Interesse.objects.all()})


def tfcs_page_view(request):
    elementos = TFC.objects.all()

    return render(request, 'portfolio/tfcs.html', {"tfcs": elementos})


@login_required
def licenciatura_nova_cadeira_view(request):
    form = CadeiraForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:licenciatura'))

    context = {'form': form}

    return render(request, 'portfolio/novacadeira.html', context)


@login_required
def licenciatura_edita_cadeira_view(request, cadeira_id):
    cadeira = Cadeira.objects.get(pk=cadeira_id)
    form = CadeiraForm(request.POST or None, instance=cadeira)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:licenciatura'))

    context = {'form': form, 'cadeira_id': cadeira_id}

    return render(request, 'portfolio/editacadeira.html', context)


@login_required
def licenciatura_apaga_cadeira_view(request, cadeira_id):
    Cadeira.objects.get(pk=cadeira_id).delete()
    return HttpResponseRedirect(reverse('portfolio:licenciatura'))

@login_required
def nova_aptidao_view(request):
    form = AptidoesECompetenciaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:aptidoes'))

    context = {'form': form}

    return render(request, 'portfolio/novaaptidao.html', context)


@login_required
def edita_aptidao_view(request, aptidao_id):
    aptidao = AptidoesECompetencia.objects.get(pk=aptidao_id)
    form = AptidoesECompetenciaForm(request.POST or None, instance=aptidao)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:aptidoes'))

    context = {'form': form, 'aptidao_id': aptidao_id}

    return render(request, 'portfolio/editaaptidao.html', context)


@login_required
def apaga_aptidao_view(request, aptidao_id):
    AptidoesECompetencia.objects.get(pk=aptidao_id).delete()
    return HttpResponseRedirect(reverse('portfolio:aptidoes'))


@login_required
def novo_projeto_view(request):
    form = ProjetoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))

    context = {'form': form}

    return render(request, 'portfolio/novoprojeto.html', context)


@login_required
def edita_projeto_view(request, projeto_id):
    projeto = Projeto.objects.get(pk=projeto_id)
    form = ProjetoForm(request.POST or None, instance=projeto)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))

    context = {'form': form, 'projeto_id': projeto_id}

    return render(request, 'portfolio/editaprojeto.html', context)


@login_required
def apaga_projeto_view(request, projeto_id):
    Projeto.objects.get(pk=projeto_id).delete()
    return HttpResponseRedirect(reverse('portfolio:projetos'))


@login_required
def nova_tecnologia_view(request):
    form = TecnologiaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:programacaowebtecnologias'))

    context = {'form': form}

    return render(request, 'portfolio/novatecnologia.html', context)


@login_required
def edita_tecnologia_view(request, tecnologia_id):
    tecnologia = Tecnologia.objects.get(pk=tecnologia_id)
    form = TecnologiaForm(request.POST or None, instance=tecnologia)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:programacaowebtecnologias'))

    context = {'form': form, 'tecnologia_id': tecnologia_id}

    return render(request, 'portfolio/editatecnologia.html', context)


@login_required
def apaga_tecnologia_view(request, tecnologia_id):
    Tecnologia.objects.get(pk=tecnologia_id).delete()
    return HttpResponseRedirect(reverse('portfolio:programacaowebtecnologias'))


@login_required
def nova_noticia_view(request):
    form = NoticiaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:noticias'))

    context = {'form': form}

    return render(request, 'portfolio/novanoticia.html', context)


@login_required
def edita_noticia_view(request, noticia_id):
    noticia = Noticia.objects.get(pk=noticia_id)
    form = NoticiaForm(request.POST or None, instance=noticia)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:noticias'))

    context = {'form': form, 'noticia_id': noticia_id}

    return render(request, 'portfolio/editanoticia.html', context)


@login_required
def apaga_noticia_view(request, noticia_id):
    Noticia.objects.get(pk=noticia_id).delete()
    return HttpResponseRedirect(reverse('portfolio:noticias'))


@login_required
def novo_laboratorio_view(request):
    form = LaboratorioForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:laboratorios'))

    context = {'form': form}

    return render(request, 'portfolio/novolaboratorio.html', context)


@login_required
def edita_laboratorio_view(request, laboratorio_id):
    laboratorio = Laboratorio.objects.get(pk=laboratorio_id)

portfolio/templates/portfolio/certificados.html
<!-- certificados.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}
	<h1>Certificados</h1>
    <p>De momento, não possuo tais documentos </p>
{% endblock %}

portfolio/templates/portfolio/competencias.html
<!-- competencias.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Competencias</h3>
    <p>texto texto texto texto texto texto texto </p>
{% endblock %}

portfolio/templates/portfolio/editacadeira.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block main %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <form action="{% url 'portfolio:licenciatura_edita_cadeira' cadeira_id %}" method="POST" class="formulario" enctype="multipart/form-data">
        {% csrf_token %}
            <h3>Editar unidade curricular</h3>

        {{ form.as_p }}
        <input type="submit" value="Gravar" class="btn btn-success">
        <a href="{% url 'portfolio:licenciatura' %}" class="btn btn-danger">Cancelar</a>
        <a href="{% url 'portfolio:licenciatura_apaga_cadeira' cadeira_id %}" class="btn btn-danger">Apagar</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/editaescola.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block main %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <form action="{% url 'portfolio:edita_escola' escola_id %}" method="POST" class="formulario" enctype="multipart/form-data">
        {% csrf_token %}
            <h3>Editar Escola</h3>

        {{ form.as_p }}
        <input type="submit" value="Gravar" class="btn btn-success">
        <a href="{% url 'portfolio:educacao' %}" class="btn btn-danger">Cancelar</a>
        <a href="{% url 'portfolio:apaga_escola' escola_id %}" class="btn btn-danger">Apagar</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/editainteresse.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block main %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <form action="{% url 'portfolio:edita_interesse' interesse_id %}" method="POST" class="formulario" enctype="multipart/form-data">
        {% csrf_token %}
            <h3>Editar Interesse</h3>

        {{ form.as_p }}
        <input type="submit" value="Gravar" class="btn btn-success">
        <a href="{% url 'portfolio:interessesehobbies' %}" class="btn btn-danger">Cancelar</a>
        <a href="{% url 'portfolio:apaga_interesse' interesse_id %}" class="btn btn-danger">Apagar</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/editatecnologia.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block main %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <form action="{% url 'portfolio:edita_tecnologia' tecnologia_id %}" method="POST" class="formulario" enctype="multipart/form-data">
        {% csrf_token %}
            <h3>Editar Tecnologia</h3>

        {{ form.as_p }}
        <input type="submit" value="Gravar" class="btn btn-success">
        <a href="{% url 'portfolio:programacaowebtecnologias' %}" class="btn btn-danger">Cancelar</a>
        <a href="{% url 'portfolio:apaga_tecnologia' tecnologia_id %}" class="btn btn-danger">Apagar</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/laboratorios.html
<!-- laboratorios.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/laboratorios.css' %}">

<h1>Laboratórios</h1>
<br>
{% for laboratorio in laboratorios %}
<div class="container">
    <div>
        <h3><a href= "{{laboratorio.link}}"> {{laboratorio.titulo}} </a></h3>
        <br>
        <p>{{laboratorio.descricao}}</p>
        <br>
        {% if request.user.is_authenticated %}
        <button class="button button1"><a href="{% url 'portfolio:edita_laboratorio' laboratorio.id %}">Editar</a></button>
        {% endif %}
    </div>
</div>
{% endfor %}
{% if request.user.is_authenticated %}
<div class=botao>
    <button class="button button2"><a href="{% url 'portfolio:novo_laboratorio' %}">Adicionar Laboratorio</a>
    </button>
</div>
{% endif %}
{% endblock %}

portfolio/templates/portfolio/licenciatura.html
<!-- licenciatura.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}

{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/licenciatura.css' %}">

<h1>Cadeiras</h1>

<br>

{% for cadeira in cadeiras %}
<div class="container">
    <div>
        <h3>{{cadeira.nome}} ({{cadeira.ano}}ºAno {{cadeira.semestre}}ºSemestre {{cadeira.anoLetivoFrequentado}})</h3>
        <br>
        <p>{{cadeira.descricao}}</p>
        <br>
        <p><b>ECTS:</b> {{cadeira.ects}}</p>

        {% for professorTeorica in cadeira.professorTeoricas %}
        <p><b>Docente Teórica:</b> {{professorTeorica}}</p>
        {% endfor %}

        {% for professorPratica in cadeira.professorPraticas %}
        <p><b>Docente Prática:</b> {{professorPratica}}</p>
        {% endfor %}

        {% if cadeira.linguagemUtilizada != None %}
        {% for linguagensUtilizadas in cadeira.linguagemUtilizada %}
        <p><b>Linguagem Lecionada:</b> {{linguagensUtilizadas}}</p>
        {% endfor %}
        {% endif %}

        {% if cadeira.projetoRealizado != None %}
        {% for projeto in cadeira.projetoRealizado %}
        <p><b>Projeto:</b> {{projeto}}</p>
        {% endfor %}
        {% endif %}

        <p><b>Rating:</b> {{cadeira.rating}} &#127775;</p>
        <br>
        <p><a href="{{cadeira.urlCadeira}}">
            <button class="button button1">Saber mais</button>
        </a></p>
        <br>
        {% if request.user.is_authenticated %}
        <button class="button button1"><a href="{% url 'portfolio:licenciatura_edita_cadeira' cadeira.id %}">Editar</a></button>
        {% endif %}
    </div>
</div>
{% endfor %}
{% if request.user.is_authenticated %}
<div class=botao>
    <button class="button button2"><a href="{% url 'portfolio:licenciatura_nova_cadeira' %}">Adicionar cadeira</a>
    </button>
</div>
{% endif %}
{% endblock %}

portfolio/templates/portfolio/novaescola.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block main %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <form action="" method="POST" class="formulario" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Nova Escola</h3>

        {{ form.as_p }}
        <input type="submit" value="Gravar" class="btn btn-success">
        <a href="{% url 'portfolio:educacao' %}" class="btn btn-danger">Cancelar</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/projetos.html
<!-- projetos.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}

{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/projetos.css' %}">

<h1>Projetos</h1>
<br>
{% for projeto in projetos %}
<div class="container">
    <div>
        <h3>{{projeto.nome}}</h3>
        <br>
        <p>{{projeto.descricao}}</p>
        <br>
        <p><b>Ano de Realização: </b>{{projeto.anoLetivoEmQueFoiRealizado}}</p>

        {% for participantes in projeto.autores %}
        <p><b>Participantes: </b>{{participantes}}</p>
        {% endfor %}

        {% if projeto.linkGitHub != None %}
        <p><b>Link do GitHub: </b><a href="{{projeto.linkGitHub}}">{{projeto.linkGitHub}}</a></p>
        {% endif %}

        {% if projeto.linkVideoYoutube != None %}
        <p><b>Vídeo de Demonstração: </b><a href="{{projeto.linkVideoYoutube}}">{{projeto.linkVideoYoutube}}</a></p>
        {% endif %}

        {% for linguagensUsadas in projeto.linguagemUsada %}
        <p><b>Linguagem Utilizada:</b> {{linguagensUsadas}}</p>
        {% endfor %}
        <br>
        {% if projeto.imagem.url != None %}
        <img src="{{projeto.imagem.url}}" width="250" height="175">
        {% endif %}
        <br>
        {% if request.user.is_authenticated %}
        <button class="button button1"><a href="{% url 'portfolio:edita_projeto' projeto.id %}">Editar</a>
        </button>
        {% endif %}
    </div>
</div>
{% endfor %}
{% if request.user.is_authenticated %}
<div class=botao>
    <button class="button button2"><a href="{% url 'portfolio:novo_projeto' %}">Adicionar projeto</a>
    </button>
</div>
{% endif %}
{% endblock %}